gooutside:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: gooutside-dev
      dataset: gooutside
      threads: 4
      timeout_seconds: 300
      location: europe-west3
      keyfile: /opt/airflow/credentials/fastapi-gcs-key.json
      priority: interactive

