version: 2

sources:
  - name: raw
    schema: gooutside_raw
    tables:
      - name: pollen_bayern_nord
      - name: air_bamberg
      - name: weather_bamberg
      - name: weather_forecast_bamberg
